tasks:
 - name: install mob tool
   init: |
    curl -sL install.mob.sh | sudo sh
 - name: run sonarqube (docker)
   command: |
    docker run -d --name sonarqube -e SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true -p 9000:9000 sonarqube:latest
