image: gitpod/workspace-dotnet

tasks:
 - name: install mob tool
   init: |
    curl -sL install.mob.sh | sudo sh
 - name: run sonarqube (docker)
   init: docker-compose pull
   command: docker-compose up -d

ports:
  - port: 9000
    onOpen: open-browser
    